version: '3.8'

services:
  offline-first-intoxication-ui:
    container_name: offline-first-intoxication-ui
    build: .
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start