micronaut:
  application:
    name: intoxicationaut
  server:
    cors:
      enabled: true

datasources:
  default:
      url: jdbc:postgresql://localhost:5430/intoxicationaut
      driverClassName: org.postgresql.Driver
      username: intoxicationaut_user
      password: intoxicationaut_pass
      schema-generate: CREATE_DROP
      dialect: POSTGRES
  liquibase:
    url: jdbc:postgresql://localhost:5430/intoxicationaut
    driverClassName: org.postgresql.Driver
    username: intoxicationaut_user
    password: intoxicationaut_pass
    maximum.pool.size: 1
liquibase:
  datasources:
    liquibase:
      enabled: true
      change-log: 'classpath:db/changelog/changelog-main.xml'
      default-schema: 'public'
